site_name: Documentation
site_url: https://orangopus.github.io/
site_description: Documentation for the Orangopus projects
theme:
  icon:
    annotation: material/star-four-points-circle
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: root
      accent: root
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: root
      accent: root

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/orangopus
      name: Orangopus on GitHub
  consent:
    title: Cookie Request
    description: >- 
      We would like to ask for your permission to use cookies for the listed purposes below. You can update your consent at any time by clicking the "manage your cookie consent" at the bottom of the page. Cookies are disabled by default.
      <br/><br/>
      Google Analytics - We use this to track your behaviour across our site, understanding your click-throughs, when you leave the site, and other useful behaviour mapping information
    actions:
      - accept
      - manage
    cookies:
      analytics:
        name: Google Analytics
        checked: false

plugins:
  - privacy
  - search

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

copyright: |
  &copy; 2024 <a href="https://www.github.com/Orangopus/" target="_blank">Orangopus</a> - <a href="#__consent">manage your cookie consent</a>